name: Event Demo 1
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependensies
        uses: actions/cache@v5
        with:
          path: ~/.npm # The path to cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install node modules
        run: npm ci
      - name: Run unit test cases
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file-name: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependensies
        uses: actions/cache@v5
        with:
          path: ~/.npm # The path to cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install node modules
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Publish JS file name
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
          # path: |
          #   path/output/bin/
          #   path/output/test-results
          #   !path/**/*.tmp
          # path: |
          #   dist
          #   package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist-files
      - name: Output filename
        run: echo ${{ needs.build.outputs.script-file-name }}
      - name: Show outputs
        run: ls
